### ISSUE TITLE
BIOS Patching not working for supported motherboard

### ISSUE THREAD

**Issue by SakuraJensen** [terminatorul/NvStrapsReBar#111]
**System**
 - Motherboard: Aorus X399 Gaming 7 WiFi
 - BIOS Version: F13d (Mobo / Resize bar natively in BIOS since f13a/unofficial f12) / 90.02.30.40.1B (GPU)
 - GPU: EVGA 2080 Ti XC Gaming 11G
 - [Y] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [Y] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [N] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [Y] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

I've tried to patch the BIOS with MMTool and UEFITool.  I've tried to recommended and latest versions of the tools.  The patched BIOS refuses to flash after failing verification in both UEFI and in at_BIOS.  Using The latest MMTool I was able to get the patched file to read in UEFI but that's as far as I've gotten.

I've included the original and patched bios files. [bios.zip](https://github.com/user-attachments/files/17576949/bios.zip)

Maybe I'm doing something wrong?

**Comment by karfelren** [comment]
the patch file has nothing to do with your bios, you just stuck on flashing the bios section

**Comment by SakuraJensen** [comment]
> the patch file has nothing to do with your bios, you just stuck on flashing the bios section

The patch literally goes directly into my BIOS.  Hence, the entire point of putting the .ffs file in.  Are you sure you read the instructions?

The problem is also flashing, obviously it's not passing the checksum verification.

**Comment by SakuraJensen** [comment]
Actually found some information on this after the fact:

https://winraid.level1techs.com/t/flashing-gigabyte-while-avoiding-invalid-bios-image/31185

**Comment by karfelren** [comment]
sorry for stepping in then and good luck

**Comment by SakuraJensen** [comment]
Got it.

Bios F13a/d introduced the verification for bios files.  But F12 did not.  Specifically the F12 internal version that had ReBAR enabled (located here: https://winraid.level1techs.com/t/request-bios-for-gigabyte-x399-aorus-gaming-7-resizable-bar/37877)

I was able to downgrade the bios to F12 using the built in BIOSBACKUP folder on the mobo.  and then flash my modified F13d bios over it.

![image](https://github.com/user-attachments/assets/3e445844-6d8c-4b18-9931-38c95f2618b6)
![image](https://github.com/user-attachments/assets/6de74e58-6d5d-4437-9e92-54f36469c308)
