### ISSUE TITLE
not founding NvStrapsReBar.exe

### ISSUE THREAD

**Issue by AliZf1d** [terminatorul/NvStrapsReBar#12]
I tried to build NvStrapsReBar.exe, but there's no Release\ subfolder for me! what could be wrong?

**Comment by AliZf1d** [comment]
Okay i'm stupid, I didn't put the last line "cmake --build . --config Release"

**Comment by Black6spdZ** [comment]
> Okay i'm stupid, I didn't put the last line "cmake --build . --config Release"

that happened to me as well.. seems the copy function of the site didn't include it for some reason
