### ISSUE TITLE
manual error

### ISSUE THREAD

**Issue by UnidentifiedTag** [terminatorul/NvStrapsReBar#2]
you are using the term "ChDir " when you should be putting "CD" putting ChDir ends in the command failing

**Comment by UnidentifiedTag** [comment]
for example  

```
If Not Defined VSCMD_VER "%ProgramFiles%\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
ChDir "%UserProfile%\edk2"
If Not Defined EDK_TOOLS_BIN edksetup.bat
ChDir NvStrapsReBar/ReBarDxe
python3 buildffs.py
```

`ChDir "%UserProfile%\edk2"`
needs changing to `ChDir "%UserProfile%\edk2"`

and `python3 buildffs.py` needs changing to `python buildffs.py`

otherwise these commands dont work for me

**Comment by UnidentifiedTag** [comment]
missing from the manual, users will need to set the path to Python and NASM 


`set PATH=%PATH%;x:\path\to\PythonXX`
`set PATH=%PATH%;x:\path\to\NASM`


to test its working correctly and x86 native tools command prompt vs is accessible to Python and NASM the following needs to be added 

`python --version`
`nasm -v`

**Comment by Felty2562** [comment]
yes also should check pip and git with cmd, add to path git and cmake too, also nasm is reccomended to be installed in C:Nasm/Nasm.exe

**Comment by UnidentifiedTag** [comment]
`set PATH=%PATH%;x:\Users\username\AppData\Local\bin\NASM`
`set PATH=%PATH%;x:\Users\username\AppData\Local\Programs\Python\Python312`
`set PATH=%PATH%;x:\Users\username\AppData\Local\Programs\Git\cmd`

please include git, only the 3 need there path pointing out every and each time the computer is restart, these paths are not saved, so users will need to redo this each restart, these are my findings

**Comment by terminatorul** [comment]
Can you test ChDir again please ? 

It is the same as CD and it should work normally.  What is wrong with it ?

**Comment by UnidentifiedTag** [comment]
> Can you test ChDir again please ?
> 
> It is the same as CD and it should work normally. What is wrong with it ?

when i was using it it wasn't working, 

however after retesting it again it does work, apologies,

you might want to still think about changing it as chdir is longer than cd, cd has always worked for me, even in dos, chdir is longer, more likely to get wrong while typing, which is likely why it didn't work the 1st time for me,  not that i want to admit that i type things wrong

**Comment by UnidentifiedTag** [comment]
this one has tripped me up alot! a real lot, i hope i get a mention

`set PATH=%PATH%;%ProgramFiles%\NASM`
doesn't work for NASM, it seems to because 
`nasm --version`
will return the version of NASM 
its only till you get to 
`ChDir "%UserProfile%\edk2"`
`edksetup.bat`
that you are told NASM is still not variable, et PATH=%PATH%; works for everything else but NASM, i've found the correct command we should be using and thats :

`set NASM_PREFIX=%ProgramFiles%\NASM`

after running the above command, NASM shows up everytime in 
`edksetup.bat`
you might need to run 
`edksetup.bat` again after the 1st time to make the warning message go away, 

this i feel is what is tripping people up, lets get : 
`set NASM_PREFIX=%ProgramFiles%\NASM` on the manual instead 

Downlaod and install [NASM](https://www.nasm.us/) and add the install directory to the PATH environment variable (in Windows Settings). The NASM installer does not show the option to add NASM to path at install time, so you will have to add it manually. NASM is by default installed at set NASM_PREFIX=%ProgramFiles%\NASM, and you should add this directory to PATH. You can change your PATH variable from Windows Settings | System | About | Advanced Windows Settings | Environment Variables | System variables | PATH | Edit... | New...

**Comment by UnidentifiedTag** [comment]
ok after looking again you need both : 
`set PATH=%PATH%;%ProgramFiles%\NASM`
and
`set NASM_PREFIX=%ProgramFiles%\NASM`

so manual needs the following edit :

Downlaod and install [NASM](https://www.nasm.us/) and add the install directory to the PATH environment variable (in Windows Settings). The NASM installer does not show the option to add NASM to path at install time, so you will have to add it manually. NASM is by default installed at `set NASM_PREFIX=%ProgramFiles%\NASM` and `set PATH=%PATH%;%ProgramFiles%\NASM`  and you should add this directory to PATH. You can change your PATH variable from Windows Settings | System | About | Advanced Windows Settings | Environment Variables | System variables | PATH | Edit... | New..

**Comment by terminatorul** [comment]
Added NASM_PREFIX to the build instructions, to fix the warning from `edksetup.bat` command. Please not NASM still works as expected even with the warnings, if you add it to PATH
