### ISSUE TITLE
Cant update Modded Bios because there is nothing found on USB drive

### ISSUE THREAD

**Issue by JACKPOT71** [terminatorul/NvStrapsReBar#30]
**System**
 - Motherboard: MSI Z490 pro a
 - BIOS Version: All i tryd
 - GPU: RTX 2070

**Description**

Describe the issue here.

Everytime i read about re-bar i think about the issue i had. My bios file has a specific ending and dont have a ending like: rom, bin, cap, bio, ft, wph, dec or something and if i open the file with UEFITool everything works fine. But if i load the ready file to a usb stick and try to flash my bios, there is nothing found on the drive. It just dont see the file in flash explorer. Is there a way to "convert" the file or what i am doing the wrong way?

There are some MSI Boards on the success list and i wonder how the people solve this ...

**Comment by JACKPOT71** [comment]
![bios](https://github.com/terminatorul/NvStrapsReBar/assets/162745518/4ac0db5a-a497-4ce1-aff1-ce458770f800)

**Comment by itasli** [comment]
I also have a MSI laptop/mb... after saving the patched rom file, you need to rename it like the original file, in my case it's `E16U7IMS.10C`, when I boot right into BIOS menu and try to flash it, it does appear but give me an error message : `Failed, Wrong Image format 11!`

**Comment by terminatorul** [comment]
Hi.

I also have issues with my MSI board, where BIOS Flashback could never read the USB stick.  I could not find a solution, but changing the CPU fixed my issue at the time. But at the time I found it helps to try as many USB sticks as you can, the older and smaller they are, the better.

Make sure you rename the modded file to the original file name. Did you use the right USB port for M-FLASH ? Can you format it to FAT / FAT32 ? Do you have a small capacity USB driver ?

Can you try the other tool flashrom ?

Since this is an Intel board, does FPT tool work for you ?

**Comment by Synaptik1** [comment]
Pls share your modified bios, because I can't patch my bios (I have same motherboard)

**Comment by JACKPOT71** [comment]
> Hi.
> 
> I also have issues with my MSI board, where BIOS Flashback could never read the USB stick. I could not find a solution, but changing the CPU also fixed the issue I had at the time. But at the time I found it helps to try as many USB sticks as you can, the older and smaller they are, the better.
> 
> Make sure you rename the modded file to the original file name. Did you use the right USB port for M-FLASH ? Can you format it to FAT / FAT32 ? Do you have a small capacity USB driver ?
> 
> Can you try the other tool flashrom ?
> 
> Since this is an Intel board, does FPT tool work for you ?

Yehaa, i managed it to flash my bios with it. I use a usb2 stick, USB Legacy in bios enabled (disabled while tweaking) and FAT format. 
I try to patch the file i created but the cmd instantly closes. I thought thats it and flash my bios. After i enable re-bar and above 4GB in Bios, i enable re-bar in nvidia profile inspector to. I run NvStrapsReBar.exe and have this happend in the picture.
CPU-Z say its not enabled. 
![Capture](https://github.com/terminatorul/NvStrapsReBar/assets/162745518/aa8c542b-8403-4809-98ad-1a708de6b519)

**Comment by JACKPOT71** [comment]
> Pls share your modified bios, because I can't patch my bios (I have same motherboard)

If i am done with it, i share it with you. With other bios tweaks i do before. Runs great.

**Comment by JACKPOT71** [comment]
Re-Bar Successful enabled. I report it later.
Thanks for your help mates.
