### ISSUE TITLE
Cant flash on to Asrock B450M Pro4

### ISSUE THREAD

**Issue by fitsfer** [terminatorul/NvStrapsReBar#33]
**System**
 - Motherboard: Asrock B450M Pro4
 - BIOS Version: 4.20
 - GPU:  GIGABYTE WINDFORCE OC GTX 1650 Super
 - [x] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

Whenever I try to flash a modded image to my bios, i get the error: "Secure Flash Check Fail!" and I'm prompted to restart.  Ive tried:

- Downgrading to a [bios version](https://www.asrock.com/mb/AMD/B450M%20Pro4/index.asp#BIOS:~:text=China-,4.20,-2020/7/9) with AGESA 1.0.0.6 beforehand
- using [UBU tool](https://winraid.level1techs.com/t/guide-how-to-flash-a-modded-ami-uefi-bios/30627#:~:text=BIOS%20properly%20flashed.-,Solution%3A,-The%20%E2%80%9CSecurity%20Flash) to try to remove the security check (the filesize doesn't change)
- different file extensions 

any help would be appreciated!

**Comment by terminatorul** [comment]
Hi

All I know are the same instructions that you linked (I don't have an Asrock board). Did you follow all 8 steps correctly ? Can you use the other method with flashrom tool ?

**Comment by terminatorul** [comment]
See also user reports here, can you do the same ?: https://github.com/terminatorul/NvStrapsReBar/issues/1#issuecomment-1913697084

**Comment by whood** [comment]
I had to use guide from reddit to flash modded bios on my Asrock B450M Steel legend. 
https://www.reddit.com/r/ASRock/comments/udn1go/comment/i7r11g1/

You don't need to download dll or rufus from provided link, just use official 3.17 version from https://rufus.ie/downloads/ and install FreeDOS instead of MSDOS.

**Comment by fitsfer** [comment]
Your solution worked! tysm <3

**Comment by ykcgw** [comment]
So, if I flash it with programmer directly connecting to the motherboard to the Bios IC, it would also work?
