### ISSUE TITLE
UEFI DXE driver status: Not loaded (0x000000000000000A)

### ISSUE THREAD

**Issue by mitix67** [terminatorul/NvStrapsReBar#44]
**System**
 - Motherboard: AORUS X570 MASTER
 - BIOS Version: F37
 - GPU: RTX 2080
 - [x] CSM Disabled 
 - [x] 4G decoding is enabled. 
 - [x] UEFIPatch is applied 
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

I have updated this file and flashed it through efiflash, with method provided in wiki. Flash was succesfull, however the program is still showing, that the driver is not present. 
DSDT pathing is not required for my mobo.

UEFI DXE driver status: Not loaded (0x000000000000000A)
<img width="646" alt="image" src="https://github.com/terminatorul/NvStrapsReBar/assets/42157705/4d58c005-9b1f-4439-81b2-e14d37a04bc5">
<img width="800" alt="image" src="https://github.com/terminatorul/NvStrapsReBar/assets/42157705/5cc22490-45c7-47f8-bf52-9497dd6e0392">
<img width="287" alt="image" src="https://github.com/terminatorul/NvStrapsReBar/assets/42157705/df45af63-1c4f-4091-936f-3a0288235e46">
<img width="581" alt="image" src="https://github.com/terminatorul/NvStrapsReBar/assets/42157705/e00f80b9-01a9-4d60-aee6-b27570d7f34c">

**Comment by terminatorul** [comment]
Does it work if you follow the instructions here ? https://github.com/xCuri0/ReBarUEFI/discussions/89#discussioncomment-8201331

Notice this uses Q-Flash in UEFI Setup to flash the new image (not efiflash)

**Comment by mitix67** [comment]
Yeah, awesome!
It worked with this method, idk why the other didn't since, I was using the modded efiflash.
