### ISSUE TITLE
Is everything all right?

### ISSUE THREAD

**Issue by AndreyRGW** [terminatorul/NvStrapsReBar#59]
![image](https://github.com/terminatorul/NvStrapsReBar/assets/50556416/c89f9d8d-ed18-48c2-ba5b-1f1baf5ad632)

Is it supposed to be that BAR0 is 16mb and BAR1 is 16gb? In NvStrapsReBar I have automatic ReBar size adjustment enabled.

P.S. I have RTX 2060 12Gb

**Comment by terminatorul** [comment]
Yes, GPU-Z output looks as expected.
Congrat'z !

**Comment by AndreyRGW** [comment]
> Yes, GPU-Z output looks as expected. Congrat'z !

Thanks!
