### ISSUE TITLE
UEFI DXE driver status: Not loaded (0x000000000000000A)

### ISSUE THREAD

**Issue by Lxstmxnd** [terminatorul/NvStrapsReBar#60]
- Motherboard: b365m-hdv
 - BIOS Version: 4.41A
 - GPU: 1660
 - CSM is turned off.
 - 4G decoding is enabled. 
 - UEFIPatch is applied )

getting error with flash bios "secure flash check fail"

**Comment by terminatorul** [comment]
See how other users managed to get things working:

https://github.com/terminatorul/NvStrapsReBar/issues/1#issuecomment-1913697084
https://github.com/terminatorul/NvStrapsReBar/issues/1#issuecomment-1996070267
https://github.com/terminatorul/NvStrapsReBar/discussions/54
