### ISSUE TITLE
Error listing display adapters: wrong PCI instance ID property value No NVIDIA GPUs present!

### ISSUE THREAD

**Issue by GeorgeKellett** [terminatorul/NvStrapsReBar#73]
**System**
 - Motherboard: Asus ROG X570-E
 - BIOS Version: 5003 (Patched as required)
 - GPU: MSI Duke 2080
 - [x] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Hello I've followed the guides and read through other issues. 
I believe I might be having a similar issue to https://github.com/terminatorul/NvStrapsReBar/discussions/11

I use English(UK) but I figured it was long enough ago where the fix is probably pushed to the latest v0.4 release.

Output:
NvStrapsReBar, based on:
ReBarState (c) 2023 xCuri0

Device instace ID: PCI\VEN_5853&DEV_1003\1&36444BD7&0&03
Application error while listing display adapters: Error listing display adapters: wrong PCI instance ID property value
No NVIDIA GPUs present!
UEFI DXE driver status: Missing GPU BAR0 Configuration (0x0b000000000000a2)
...

Does anyone have any ideas?
Thank you.

**Comment by terminatorul** [comment]
It is similar to https://github.com/terminatorul/NvStrapsReBar/discussions/11, but a different property is at fault. The original issue https://github.com/terminatorul/NvStrapsReBar/discussions/11 is indeed fixed in the latest version.

Looks like the PCI subsystem ID is missing from the property value. See the SUBSYS_ string IDs in the expected property value below:
```
PCI \ VEN_10DE & DEV_1E07 & SUBSYS_37151462 & REV_A1 \ 4 & 324A30C7 & 0 & 0019
```

Does GPU-Z show the PCI subsystem ID ? Or HWiNFO64 ?

Fixing this requires a patch in NvStrapsReBar.exe, to make the subsystem ID optional in the regular expression in file `DeviceList.ixx`, variable `pciInstanceRegexp` (currently at line 327).

**Comment by terminatorul** [comment]
Can you also show the Hardware IDs property in Device Manager, like this ?
![image](https://github.com/terminatorul/NvStrapsReBar/assets/378924/a1d4e249-0596-4dbb-9b2a-6f60dda00e17)

**Comment by GeorgeKellett** [comment]
Yes Sir,

I hope the following information is what you need.
PCI\VEN_10DE&DEV_1E87&SUBSYS_37211462&REV_A1\4&1D81E16&0&0019

![image](https://github.com/terminatorul/NvStrapsReBar/assets/165169448/2f7d0099-e353-4733-8664-e5b70c5b5ea4)
![image](https://github.com/terminatorul/NvStrapsReBar/assets/165169448/b8211570-f92d-4262-8d42-07e3c09ac8f8)

How can I patch the program without needing to recompile? I'd rather avoid installing all the dependencies to compile it myself.
Thank you for the help so far.

**Comment by terminatorul** [comment]
Your GPU looks fine !

The missing PCI subsystem ID is for a different device in your system, from XenSource (virtualization technology) with PCI ID 5853:1003. I could not find this specific PCI ID on Google, do you know what device in your system has this ID ? Can you remove it temporarily ? This will allow you to enable ReBAR, and then you can add the device back.

**Comment by GeorgeKellett** [comment]
I have Citrix workspace installed for my work at home environment. Citrix own XenServer it's got to be related.

Thanks for the pointer. It's late here I'll get back to you when I've had a chance to remove all my work software and try again!

**Comment by GeorgeKellett** [comment]
I got restless and figured I'd fix it now.
Simply uninstalling "Citrix Indirect display adapter" from device manager > display adapters, ticking to remove driver fixed it.
I guess it found that and errored out.

I could probably reinstall it but it's only for the "Citrix casting" feature I don't need.

Thanks for the quick resolution.
