### ISSUE TITLE
 UEFIpatch vs ROG-MAXIMUS-XI-EXTREME-ASUS-2004  Add a description

### ISSUE THREAD

**Issue by Tazo83** [terminatorul/NvStrapsReBar#87]
**System**
 - Motherboard: ROG-MAXIMUS-XI-EXTREME-ASUS-2004
 - BIOS Version: 2004
 - GPU: Zotac 2080 Ti
 - [ yes] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ yes] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ Issue ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ yes] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

![image](https://github.com/terminatorul/NvStrapsReBar/assets/42385505/7490c9ed-30bb-4767-bf1d-4080636fa465)

Bios Offical file for MotherBoard:>>  https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/ROG-MAXIMUS-XI-EXTREME-ASUS-2004.ZIP?model=ROG%20MAXIMUS%20XI%20EXTREME

I have tried UEFItool ver 28 and the new one also I tried using mmtool the main issue is the patcher always  say this error: 

C:\Rebar\UEFIPatch.exe ROG-MAXIMUS-XI-EXTREME-ASUS-2004.CAP

parseImageFile: Aptio capsule signature may become invalid after image modifications
parseIntelImage: unknown flash descriptor version 0.0
parseBios: unaligned revision 2 volume
parseFile: non-empty pad-file contents will be destroyed after volume modifications
No patches can be applied to input file

even the official motherboard file without any UEFITool or MMtool, when I tried to use UEFIpatch on it was giving me the same error

I don't know what Is the cause of this issue but if there is any hope for me to have Rebar on my 2080 ti please explain to me 

thank you

**Comment by RipperPix00** [comment]
I don't think you need to use UEFI patch because your motherboard is not very old.

**Comment by Yorrannn** [comment]
I have the exact same setup, only use NvStrapsRebar on BIOS 2004, UEFI Patch is not necessary. I have the patched BIOS still saved.  Just follow https://github.com/xCuri0/ReBarUEFI/wiki/Adding-FFS-module

![image](https://github.com/user-attachments/assets/45687017-16e0-4d1e-83b2-92ae8f235141)

**Comment by Tazo83** [comment]
i just tried adding  the NvStrapsRebar to the bios and saving that as new bios then when i tried to load it from the motherboard flashing tool it said my new file is not a proper bios file;x
 this is my bios file 
 https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/ROG-MAXIMUS-XI-EXTREME-ASUS-2004.ZIP?model=ROG%20MAXIMUS%20XI%20EXTREME

I would love to test out your bios file maybe it works, been trying for a year now with no luck

**Comment by Yorrannn** [comment]
Try to use BIOS Flashback on your MB. You can't flash it like a normal bios update. There is a USB port with BIOS above it. Read the manual on how to use it. I had the same problem..

https://www.asus.com/support/faq/1038568/

**Comment by Tazo83** [comment]
Man I dont know how I can say thank you 

![image](https://github.com/user-attachments/assets/2cabac67-8ecc-4c72-85f8-15424015fbfe)

![image](https://github.com/user-attachments/assets/9e00ea3e-33d9-4fa3-8cb7-c7a73ae3f07d)

All this time I was going into the bios setting and using their flash tool included in bios, but after reading the link above I found out that I was only missing this force load bios ---> shutdown, hold the bios button 3 sec until flash light blink and when it stops just normal boot and BOOM MAGIC all good now I need to test on some games and see myself :D

Again thank you, sir. It is one of the best online support there 👍

**Comment by Yorrannn** [comment]
No problem, glad i could help :)
