### ISSUE TITLE
Is it mandatory to enable Above 4G Decoding?

### ISSUE THREAD

**Issue by 1NFERR** [terminatorul/NvStrapsReBar#92]
Hi everyone. I wanted to install NvStrapsReBar, but in the settings of my motherboard (Lenovo 36E7) there is no option to enable Above 4G Decoding, even in hidden settings. I can only enable "Above 4GB MMIO BIOS assignment" in hidden settings.
Is it mandatory to enable Above 4G Decoding? In ReBarUEFI, not enabling this option will only limit the maximum number of GB BARs (somewhere up to 1 GB)

**Comment by mikehell87** [comment]
Hello There, can you please help me or give me advices to suceed on this process with lenovo m910s sff (motherborard 3106) ? Thanks you !
